name: Backend Code Integration

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run the backend test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the tests
        run: make api_test
